Repositorioblog/Blog_noticias/Blog_noticias/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views




from . import views

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', views.home, name = 'path_home'),
    
    path('cultura/', include('articulos.urls')),

    path('ckeditor/', include('ckeditor_uploader.urls')),

    path('comentarios/', include('comentarios.urls')),
    
    path('usuarios/', include('usuarios.urls')),

    path('nosotros/', include('nosotros.urls')),

    path('contacto/', include('contacto.urls')),

    path('agenda/', include('agenda.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Repositorioblog/Blog_noticias/apps/nosotros/urls.py
from django.urls import path
from . import views

app_name = 'nosotros'

urlpatterns = [

    path('', views.lista_nosotros, name = 'path_nosotros_main'),

    path('crear/', views.CrearNosotros.as_view(), name='path_crear_nosotros'),

    

    
  
    path('<slug:nosotros_slug>/editar/', views.EditarNosotros.as_view(), name='path_editar_nosotros'),

    path('<slug:nosotros_slug>/borrar/', views.BorrarNosotros.as_view(), name='path_borrar_nosotros'),

    path('<slug:nosotros_slug>/', views.detalle_nosotros, name='path_detalle_nosotros'),
    


]

Repositorioblog/Blog_noticias/apps/nosotros/models.py
from django.db import models
from django.utils.text import slugify
from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import RichTextUploadingField
from django.urls import reverse
from categorias.models import Categoria
from django.contrib.auth.models import User


class Nosotros(models.Model):
    creado = models.DateTimeField(auto_now_add=True)

    modificado = models.DateTimeField(auto_now=True)

    titulo = models.CharField(max_length=40)

    slug = models.SlugField(max_length=50, unique=True, blank=True, help_text="se genera automáticamente.")

    contenido = RichTextUploadingField()

    imagen = models.ImageField(upload_to= 'nosotros/', null=False, blank=False,default='articulos/default_img_articulo.jpg')

    class Meta:
        ordering = ['creado'] #mas viejo primero 

    def __str__(self):
        return self.titulo
    
    def save(self, *args, **kwargs):
        from django.utils.text import slugify
        if not self.slug:
            self.slug = slugify(self.titulo)

            original_slug = self.slug
            Klass = self.__class__
            num = 1

            while Klass.objects.filter(slug=self.slug).exists():
                self.slug = f"{original_slug}--{num}"
                num += 1
        super().save(*args,**kwargs)
    
    def get_absolute_url(self):
        return reverse('nosotros:path_detalle_nosotros', kwargs={'nosotros_slug': self.slug})
    
    def __str__(self):
        return self.titulo

Repositorioblog/Blog_noticias/apps/nosotros/forms.py
from django import forms
from .models import Nosotros


class FormularioCrearNosotros(forms.ModelForm):

    class Meta:
        model = Nosotros
        fields = ['titulo', 'contenido', 'imagen']

Repositorioblog/Blog_noticias/apps/nosotros/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from .models import Nosotros
from .forms import FormularioCrearNosotros

from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin



# Create your views here.





def lista_nosotros(request):
    todos_los_nosotros = Nosotros.objects.all().order_by('creado')

    about_principal = todos_los_nosotros.first() #tengo que crear primero el principal we

    colectividades = todos_los_nosotros.exclude(pk=about_principal.pk)

    contexto = {
        'about_principal': about_principal,
        'colectividades': colectividades,
    }

    return render(request, 'nosotros/nosotros_main.html', contexto)

def detalle_nosotros(request, nosotros_slug):
    nosotros = get_object_or_404(Nosotros, slug=nosotros_slug)

      
    contexto = {
        'nosotros': nosotros,
        }

    return render(request, 'nosotros/detalle_nosotros.html', contexto)

class CrearNosotros(LoginRequiredMixin, UserPassesTestMixin, CreateView):
    model = Nosotros
    template_name = 'nosotros/crear_nosotros.html'
    form_class = FormularioCrearNosotros
    success_url = reverse_lazy('nosotros:path_nosotros_main')

    def test_func(self):
        return self.request.user.is_staff
    
class EditarNosotros(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Nosotros
    template_name = 'nosotros/editar_nosotros.html'
    form_class = FormularioCrearNosotros
    slug_url_kwarg = 'nosotros_slug'
    context_object_name = 'nosotros'
    def get_success_url(self):
        return reverse_lazy('nosotros:path_detalle_nosotros', kwargs={'nosotros_slug': self.object.slug})
    def test_func(self):
        return self.request.user.is_staff
    
class BorrarNosotros(LoginRequiredMixin,UserPassesTestMixin, DeleteView):
    model = Nosotros
    template_name = 'nosotros/borrar_nosotros.html'
    success_url = reverse_lazy('nosotros:path_nosotros_main')
    slug_url_kwarg = 'nosotros_slug'
    context_object_name = 'nosotros'

    def test_func(self):
        return self.request.user.is_staff

Repositorioblog/Blog_noticias/templates/nosotros/borrar_nosotros.html
{% extends 'base.html' %}
{% load static %}

{% block content %}


        <!-- inicio modulo
        ================================================== -->


    <div class="s-content content">
        <main class="row content__page">
            <article class="column large-full entry format-standard">
                <h2>Eliminar Sobre Nosotros</h2>

                <p>¿Estás seguro que deseas eliminar este segmento:</p>
                <p><strong>"{{ object.titulo }}"</strong>?</p>
                
                <p>Esta acción es <strong style="color: rgb(236, 56, 56);">irreversible</strong>.</p>

                <form method="post">
                    {% csrf_token %}
                    

                    <button type="submit" class="btn btn--primary" >ELIMINAR</button>
                            
                    <a href="{% url 'nosotros:path_detalle_nosotros' nosotros_slug=nosotros.slug %}" class="btn btn--secondary">CANCELAR</a>
                </form>
            </article>
        </main>
    </div>


{% endblock content %}

Repositorioblog/Blog_noticias/templates/nosotros/crear_nosotros.html
{% extends 'base.html' %}
{% block content %}

    <div class="s-content content">
        <main class="row content__page">
            <article class="column large-full entry format-standard">
                <h2>Crear Nuevo Sobre Nosotros</h2>
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}

                    {{ form.as_p }}

                    <button type="submit" class="btn btn--primary">Crear</button>
                </form>
            </article>
        </main>
    </div>
    
    {{ form.media }}

{% endblock %}

Repositorioblog/Blog_noticias/templates/nosotros/detalle_nosotros.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

        <!-- inicio modulo
        ================================================== -->

    <div class="s-content content">
            <main class="row content__page">
                <article class="column large-full entry format-standard">

                    <div class="media-wrap entry__media">
                        <div class="entry__post-thumb">
                            <img src="{{ nosotros.imagen.url }}" alt="{{ nosotros.titulo }}">
                        </div>
                    </div>

                    <div class="content__page-header entry__header">
                        <h1 class="display-1 entry__title">
                            {{ nosotros.titulo }}
                        </h1>
                        
                        {% if user.is_staff %}
                        <ul class="entry__header-meta">
                            <li>
                                <a href="{% url 'nosotros:path_editar_nosotros' nosotros_slug=nosotros.slug %}" class="btn full-width">Editar</a>
                            </li>
                            <li>
                                <a href="{% url 'nosotros:path_borrar_nosotros' nosotros_slug=nosotros.slug %}" class="btn btn--primary full-width">Eliminar</a>
                            </li>
                        </ul>
                        {% endif %}
                    </div>

                    <div class="entry__content">
                        <p class="lead drop-cap">
                            {{ nosotros.contenido|safe }}
                        </p>
                    </div>

                </article>
            </main>
        </div>



{% endblock content %}

Repositorioblog/Blog_noticias/templates/nosotros/editar_nosotros.html
{% extends 'base.html' %}
{% load static %}

{% block content %}


        <!-- inicio modulo
        ================================================== -->

    <div class="s-content content">
        <main class="row content__page">
            <article class="column large-full entry format-standard">
                <h2>Editar Sobre Nosotros: {{ nosostros.titulo }}</h2>
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}

                    {{ form.as_p }}

                    <button type="submit" class="btn btn--primary">Guardar cambios</button>
                    <a href="{% url 'nosotros:path_detalle_nosotros' nosotros_slug=nosotros.slug %}" class="btn btn--secondary">Cancelar</a>
                </form>
            </article>
        </main>
    </div>

    

    {{form.media}}


{% endblock content %}

Repositorioblog/Blog_noticias/templates/nosotros/nosotros_main.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

    <div class="s-content content">
        <main class="row content__page">
            
            {% if about_principal %}
                <article class="column large-full entry format-standard">
                    <div class="media-wrap entry__media">
                        <div class="entry__post-thumb">
                            <img src="{{ about_principal.imagen.url }}" alt="{{ about_principal.titulo }}">
                        </div>
                    </div>

                    <div class="content__page-header entry__header">
                        <h1 class="display-1 entry__title">
                            {{ about_principal.titulo }}
                        </h1>
                        {% if user.is_staff %}  
                            <ul class="entry__header-meta">
                                <li>
                                    <a href="{% url 'nosotros:path_editar_nosotros' nosotros_slug=about_principal.slug %}" class="btn full-width">Editar</a>
                                </li>
                                
                            </ul>
                        {% endif %}
                    </div>
                    
                    <div class="entry__content">
                        <p class="lead drop-cap">
                            {{ about_principal.contenido|safe }}
                        </p>
                    </div>
                </article>
            {% endif %} 
        </main>
            <hr>
            <div class="masonry-wrap">
                <div class="masonry">
                    <div class="grid-sizer"></div>
                    
                    {% for nosotros in colectividades %} 
                    <article class="masonry__brick entry format-standard animate-this">
                        <div class="entry__thumb">
                            <a href="{% url 'nosotros:path_detalle_nosotros' nosotros_slug=nosotros.slug %}" class="entry__thumb-link">
                                <img src="{{ nosotros.imagen.url }}"  alt="{{ nosotros.titulo }}">
                            </a>
                        </div>
                        
                        <div class="entry__text">
                            <div class="entry__header">
                                <h2 class="entry__title"><a href="{% url 'nosotros:path_detalle_nosotros' nosotros_slug=nosotros.slug %}">{{ nosotros.titulo }}</a></h2>
                            </div>
                            <br>
                            <div class="entry__excerpt">
                                <a href="{% url 'nosotros:path_detalle_nosotros' nosotros_slug=nosotros.slug %}" class="btn btn--primary u-fullwidth">Conocer más</a>
                            </div>
                        </div>
                    </article>
                {% empty %}
                    <p>No hay colectividades disponibles.</p>
                {% endfor %}
                </div>        
            </div>



{% endblock content %}