Repositorioblog/Blog_noticias/Blog_noticias/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views




from . import views

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', views.home, name = 'path_home'),
    
    path('cultura/', include('articulos.urls')),

    path('ckeditor/', include('ckeditor_uploader.urls')),

    path('comentarios/', include('comentarios.urls')),
    
    path('usuarios/', include('usuarios.urls')),

    path('nosotros/', include('nosotros.urls')),

    path('contacto/', include('contacto.urls')),

    path('agenda/', include('agenda.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Repositorioblog/Blog_noticias/apps/articulos/urls.py
from django.urls import path
from . import views

app_name = 'articulos'

urlpatterns = [
    path('', views.lista_articulos, name='path_lista_home'),

    path('cultura', views.lista_articulos, name = 'path_lista_articulos'),

    path('categoria/<slug:categoria_slug>/', views.lista_articulos, name = 'path_lista_articulos_categoria'),

     path('colectividad/<slug:colectividad_slug>/', views.lista_articulos, name='path_lista_articulos_colectividad'), #mismo que cat

    path('articulo/<slug:articulo_slug>/', views.detalle_articulo, name='path_detalle_articulo'),

    path('crear/', views.CrearArticulo.as_view(), name='path_crear_articulo'),
  
    path('<slug:articulo_slug>/editar/', views.EditarArticulo.as_view(), name='path_editar_articulo'),

    path('<slug:articulo_slug>/borrar/', views.BorrarArticulo.as_view(), name='path_borrar_articulo'),
    
    
    

]

Repositorioblog/Blog_noticias/apps/comentarios/urls.py
from django.urls import path
from . import views

app_name = 'comentarios'


urlpatterns = [
    path('<slug:articulo_slug>/add/', views.add_comentario, name='path_add_comentario'),

    path('<slug:articulo_slug>/<int:comentario_id>/edit/', views.edit_comentario, name='path_edit_comentario'),

    path('<slug:articulo_slug>/<int:comentario_id>/delete/', views.delete_comentario, name='path_delete_comentario'),



    
]

Repositorioblog/Blog_noticias/apps/usuarios/urls.py
from django.urls import path

from django.contrib.auth import views as auth

from . import views

app_name = 'usuarios'



urlpatterns = [
    path('login/', auth.LoginView.as_view(template_name='usuarios/login.html'),name = 'path_login'),

    path('logout/', auth.LogoutView.as_view(),name = 'path_logout'),

    path('registro/',views.RegistroUsuario.as_view(), name = 'path_registro'),
]

    

Repositorioblog/Blog_noticias/apps/articulos/models.py
from django.db import models
from django.utils.text import slugify
from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import RichTextUploadingField
from django.urls import reverse
from categorias.models import Categoria
from django.contrib.auth.models import User
# Create your models here.

class Articulo(models.Model):
    creado = models.DateTimeField(auto_now_add=True)

    modificado = models.DateTimeField(auto_now=True)

    titulo = models.CharField(max_length=150)

    slug = models.SlugField(max_length=150, unique=True, blank=True, help_text="Slug para la URL del artículo, se genera automáticamente.")
    #https://docs.djangoproject.com/en/5.0/ref/urls/#path-converters
    
    colectividad = models.ForeignKey(Categoria, on_delete=models.SET_NULL, null=True, blank=True, related_name='colectividad')
    
    autor = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True, related_name='articulos_creados')

    descripcion = models.CharField(max_length=300) #resumen para mostrar en el home

    contenido = RichTextUploadingField()
    
    imagen = models.ImageField(upload_to= 'articulos/', null=False, blank=False,default='articulos/default_img_articulo.jpg')

    comentarios_habilitados = models.BooleanField(default=True)

    
    categoria = models.ForeignKey(Categoria, on_delete=models.SET_NULL, null=True, blank=True, related_name='articulos')

    
 

    

    class Meta:
        ordering = ['-creado'] # Ordena MAS nuevo primero
        

    def __str__(self):
        return self.titulo

    def save(self, *args, **kwargs): 
        from django.utils.text import slugify
        if not self.slug: 
            self.slug = slugify(self.titulo)
            
            original_slug = self.slug
            Klass = self.__class__
            num = 1
            
            while Klass.objects.filter(slug=self.slug).exists():
                self.slug = f"{original_slug}-{num}"
                num += 1
        super().save(*args, **kwargs)


    def get_absolute_url(self):
            return reverse('articulos:path_detalle_articulo', kwargs={'articulo_slug': self.slug})

Repositorioblog/Blog_noticias/apps/articulos/forms.py
from django import forms
from .models import Articulo
from categorias.models import Categoria, TipoCategoria

class FormularioCrearArticulo(forms.ModelForm):
    
    class Meta:
        model = Articulo
        fields = ['titulo',  'imagen',  'descripcion', 'contenido', 'categoria', 'colectividad', ]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['categoria'].queryset = Categoria.objects.filter(tipos__nombre='Cultura')
        self.fields['categoria'].empty_label = "Selecciona una categoría"
        self.fields['categoria'].required = False
        
        self.fields['colectividad'].queryset = Categoria.objects.filter(tipos__nombre='Colectividad')
        self.fields['colectividad'].empty_label = "Selecciona una colectividad"
        self.fields['colectividad'].required = False

Repositorioblog/Blog_noticias/apps/articulos/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.core.paginator import Paginator
from .models import Articulo
from .forms import FormularioCrearArticulo

from categorias.models import Categoria, TipoCategoria

from comentarios.forms import ComentarioForm

from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin




def lista_articulos(request, categoria_slug=None, colectividad_slug=None): #puede tener o no una categoria articulos/cat 
    todos_los_articulos = Articulo.objects.all().order_by('-creado') # *** nuevos primero

    categoria_actual = None
    if categoria_slug: #si categoriaslug tiene un valor,  
        categoria_actual = get_object_or_404(Categoria, slug=categoria_slug) #busca cat o da error404
        todos_los_articulos = todos_los_articulos.filter(categoria=categoria_actual) #filtra todos los art con current cat
    elif colectividad_slug:
        colectividad_actual = get_object_or_404(Categoria, slug=colectividad_slug)
        todos_los_articulos = todos_los_articulos.filter(colectividad=colectividad_actual)

    


    ordenar_por = request.GET.get('order_by', 'newest')
    if ordenar_por == 'oldest':
        todos_los_articulos = todos_los_articulos.order_by('creado') #viejos primero
    else:
        todos_los_articulos = todos_los_articulos.order_by('-creado') #nuevos

    articulos_por_pagina = 12
    paginator = Paginator(todos_los_articulos,articulos_por_pagina) #le doy todos los art, luego cuantos quiero por pag

    page_number = request.GET.get('page') #obtiene el numero de pag de la url y si no hay es la primera
    page_obj = paginator.get_page(page_number) #Obtenemos el objeto Page (una parte de la lista de art para la página actual)

   

    
    contexto = {
        'page_obj': page_obj,
        'categoria_actual': categoria_actual,
        'ordenar_por': ordenar_por, 
        'colectividad_actual': categoria_actual,
        
    }

    return render(request, 'articulos/lista_articulos.html', contexto)




def detalle_articulo(request, articulo_slug):
    articulo = get_object_or_404(Articulo, slug=articulo_slug)

    articulo_relacionado_colectividad = None
    if articulo.colectividad:
        articulo_relacionado_colectividad = Articulo.objects.filter(colectividad=articulo.colectividad).exclude(pk=articulo.pk).first()

    articulo_relacionado_categoria = None
    if articulo.categoria:
        articulos_de_la_categoria = Articulo.objects.filter(categoria=articulo.categoria).exclude(pk=articulo.pk)
        if articulo_relacionado_colectividad:
            articulos_de_la_categoria = articulos_de_la_categoria.exclude(pk=articulo_relacionado_colectividad.pk)

        articulo_relacionado_categoria = articulos_de_la_categoria.first()


    comentarios = articulo.comentarios.all()
    form_comentario = ComentarioForm()

    

    contexto = {
        'articulo': articulo,
        'comentarios':comentarios,
        'form_comentario': form_comentario,
        'articulo_relacionado_colectividad': articulo_relacionado_colectividad,
        'articulo_relacionado_categoria': articulo_relacionado_categoria,
    }

    return render(request, 'articulos/detalle_articulo.html', contexto)


class CrearArticulo(LoginRequiredMixin,UserPassesTestMixin,CreateView):
    model = Articulo
    template_name = 'articulos/crear_articulo.html'
    form_class = FormularioCrearArticulo
    success_url = reverse_lazy('articulos:path_lista_articulos')

    def test_func(self):
        return self.request.user.is_staff

class EditarArticulo(LoginRequiredMixin,UserPassesTestMixin,UpdateView):
    model = Articulo
    template_name = 'articulos/editar_articulo.html'
    form_class = FormularioCrearArticulo
    slug_url_kwarg = 'articulo_slug' # slug en lhgar de pk ///
    context_object_name = 'articulo' #el objeto en el contexto del template 
    def get_success_url(self):
        return reverse_lazy('articulos:path_detalle_articulo', kwargs={'articulo_slug': self.object.slug}) # self.object.slug = el slug del art que se edito
    def test_func(self):
        return self.request.user.is_staff

    

class BorrarArticulo(LoginRequiredMixin,UserPassesTestMixin,DeleteView):
    model = Articulo
    template_name = 'articulos/borrar_articulo.html'
    success_url = reverse_lazy('articulos:path_lista_articulos')
    slug_url_kwarg = 'articulo_slug'
    context_object_name = 'articulo'
    
    def test_func(self):
        return self.request.user.is_staff

Repositorioblog/Blog_noticias/templates/articulos/borrar_articulo.html
{% extends 'base.html' %}
{% load static %}

{% block content %}


        <!-- inicio modulo
        ================================================== -->



<div class="s-content content">
    <main class="row content__page">
        <article class="column large-full entry format-standard">
            <h2>Eliminar Artículo</h2>

            <p>¿Estás seguro que deseas eliminar el artículo:</p>
            <p><strong>"{{ object.titulo }}"</strong>?</p>
            
            <p>Esta acción es <strong style="color: rgb(236, 56, 56);">irreversible</strong>.</p>

            <form method="post">
                {% csrf_token %}
                

                <button type="submit" class="btn btn--primary" >ELIMINAR</button>
                        
                <a href="{% url 'articulos:path_detalle_articulo' articulo_slug=object.slug %}" class="btn btn--secondary">CANCELAR</a>
            </form>
        </article>
    </main>
</div>


{% endblock content %}

Repositorioblog/Blog_noticias/templates/articulos/crear_articulo.html
{% extends 'base.html' %}
{% load static %}

{% block content %}


        <!-- inicio modulo
        ================================================== -->


        
    

    <div class="s-content content">
        <main class="row content__page">
            <article class="column large-full entry format-standard">
                <h2>Crear Nuevo Artículo</h2>
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}

                    {{ form.as_p }}

                    <button type="submit" class="btn btn--primary">Crear Artículo</button>
                </form>
            </article>
        </main>
    </div>
    {{ form.media}}

{% endblock content %}

Repositorioblog/Blog_noticias/templates/articulos/detalle_articulo.html
{% extends 'base.html' %}
{% load static %}
{% load static youtube_filters %}

{% block content %}

        <!-- inicio modulo
        ================================================== -->

<div class="s-content content">
    <main class="row content__page">
            <article class="column large-full entry format-standard">

                <div class="media-wrap entry__media">
                    <div class="entry__post-thumb">
                        <!--Imagen principal del artículo  misma que home -->
                        <img src="{{ articulo.imagen.url }}" alt="{{ articulo.titulo }}">
                    </div>
                </div>

                <div class="content__page-header entry__header">
                    
                    <h1 class="display-1 entry__title">
                        {{ articulo.titulo }}
                    </h1>
                    <ul class="entry__header-meta">
                        <!-- Autor del artículo - categoria colectividad-->
                         
                        <li class="author">
                            {% if articulo.colectividad %}
                            Por <a href="{% url 'articulos:path_lista_articulos_colectividad' colectividad_slug=articulo.colectividad.slug %}">{{ articulo.colectividad.nombre }}</a></li>
                            {% endif %}
                        {% if user.is_staff %}

                        <li class="author">Autor {{ articulo.autor.username }}</li>
                        
                        {% endif %}
                        
                        
                        
                        
                        <li class="cat-links">
                            <a href="{% url 'articulos:path_lista_articulos' %}">Cultura</a>
                            {% if articulo.categoria %}
                                <a href="{% url 'articulos:path_lista_articulos_categoria' categoria_slug=articulo.categoria.slug %}">{{ articulo.categoria.nombre }}</a> 
                            {% endif %}
                        </li>
                        <li class="date">{{ articulo.creado|date:"d M Y" }}</li>
                    </ul>
                    
                                                    
                                                    
                    {% if user.is_staff %}                                
                    <ul class="entry__header-meta">
                        
                        <li>
                            
                            <a href="{% url 'articulos:path_editar_articulo' articulo_slug=articulo.slug %}" class="btn full-width">Editar Artículo</a>
                            
                        </li>
                        <li>
                            
                            <a href="{% url 'articulos:path_borrar_articulo' articulo_slug=articulo.slug %}" class="btn btn--primary full-width" >Eliminar Artículo</a>
                            
                        </li>
                        
                    </ul>
                    
                </div> <div class="entry__content">
                    {% endif %}
                    
                    <p class="lead drop-cap">
                        {{ articulo.contenido|safe }} <!-- el safe para el richtextfield -->
                    </p>

                    {% if articulo.youtube_url %}
                        <div class="youtube-video">
                        <iframe width="560" height="315" src="{{ articulo.youtube_url|youtube_embed_url }}" 
                                frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" 
                                allowfullscreen></iframe>
                        </div>
                    {% endif %}
                    
                    
                </div> 
                <div class="entry__related">
                    <h3 class="h2">Artículos Relacionados</h3>
                    <ul class="related">
                        
                        {% if articulo_relacionado_colectividad %}

                            <li class="related__item">
                                <a href="{% url 'articulos:path_detalle_articulo' articulo_slug=articulo_relacionado_colectividad.slug %}" class="related__link">
                                    <img src="{{ articulo_relacionado_colectividad.imagen.url }}" alt="{{ articulo_relacionado_colectividad.titulo }}">
                                </a>
                                <h5 class="related__post-title">{{ articulo_relacionado_colectividad.titulo }}</h5>
                                <span class="entry__meta-cat">
                                    {% if articulo_relacionado_colectividad.colectividad %}
                                        <a href="{% url 'articulos:path_lista_articulos_colectividad' colectividad_slug=articulo_relacionado_colectividad.colectividad.slug %}">
                                            {{ articulo_relacionado_colectividad.colectividad.nombre }}
                                        </a>
                                    {% endif %}
                                        <a href="{% url 'articulos:path_lista_articulos' %}">Cultura, </a>
                                    {% if articulo_relacionado_colectividad.categoria %}
                                        <a href="{% url 'articulos:path_lista_articulos_categoria' categoria_slug=articulo_relacionado_colectividad.categoria.slug %}">
                                            {{ articulo_relacionado_colectividad.categoria.nombre }}
                                        </a>
                                    {% endif %}
                                </span>
                            </li>
                        {% endif %}

                        {% if articulo_relacionado_categoria %}
                            <li class="related__item">
                                <a href="{% url 'articulos:path_detalle_articulo' articulo_slug=articulo_relacionado_categoria.slug %}" class="related__link">
                                    <img src="{{ articulo_relacionado_categoria.imagen.url }}" alt="{{ articulo_relacionado_categoria.titulo }}">
                                </a>
                                <h5 class="related__post-title">{{ articulo_relacionado_categoria.titulo }}</h5>
                                <span class="entry__meta-cat">
                                    {% if articulo_relacionado_categoria.colectividad %}
                                        <a href="{% url 'articulos:path_lista_articulos_colectividad' colectividad_slug=articulo_relacionado_categoria.colectividad.slug %}">
                                            {{ articulo_relacionado_categoria.colectividad.nombre }}
                                        </a>
                                    {% endif %}
                                        <a href="{% url 'articulos:path_lista_articulos' %}">Cultura, </a>
                                    {% if articulo_relacionado_categoria.categoria %}
                                        <a href="{% url 'articulos:path_lista_articulos_categoria' categoria_slug=articulo_relacionado_categoria.categoria.slug %}">
                                            {{ articulo_relacionado_categoria.categoria.nombre }}
                                        </a>
                                    {% endif %}
                                </span>
                            </li>
                        {% endif %}

                    </ul>
                </div>
            </article> {# Sección de comentarios #}
        <div class="comments-wrap">

            <div id="comments" class="column large-12">

                <h3 class="h2">{{ comentarios|length }} Comentario{% if comentarios|length != 1 %}s{% endif %}</h3> 
                
                <ol class="commentlist">
                    {% if comentarios %}
                        {% for comentario in comentarios %}
                            <li class="depth-1 comment">
                                

                                <div class="comment__content">
                                    <div class="comment__info">
                                        <div class="comment__author">{{ comentario.autor.username }}</div> 
                                        <div class="comment__meta">
                                            <div class="comment__time">{{ comentario.creado|date:"d M Y" }}</div> 
                                            <div class="comment__reply">
                                                {% if user.is_authenticated%}
                                                    <p>
                                                        {% if user == comentario.autor %}

                                                            <a href="{% url 'comentarios:path_edit_comentario' articulo_slug=articulo.slug comentario_id=comentario.id %}">Editar</a>
                                                        
                                                        {% endif %}
                                                            <br>
                                                        {% if user == comentario.autor or user.is_staff %}
                                                            
                                                            <a class="comment-reply-link" href="{% url 'comentarios:path_delete_comentario'  articulo_slug=articulo.slug comentario_id=comentario.id %}">Eliminar</a>

                                                        {% endif %}    
                                                    </p>
                                                   
                                                {% endif %}
                                            </div>
                                        </div>
                                    </div>
                                    <div class="comment__text">
                                        <p>{{ comentario.contenido|linebreaksbr }}</p> 
                                    </div>
                                </div>
                            
                            </li>
                        {% endfor %}
                    {% else %}
                        <p>Este artículo aún no tiene comentarios.</p>
                    {% endif %}
                </ol>
            </div>
            <div class="column large-12 comment-respond">
                <div id="respond">
                        <h3 class="h5">Añadir Comentario <span>Tu dirección de correo no será publicada</span></h3>
                
                        {% if user.is_authenticated %}
                            <form name="contactForm" id="contactForm" method="post" action="{% url 'comentarios:path_add_comentario' articulo_slug=articulo.slug %}" autocomplete="off">
                                {% csrf_token %} 
                                <fieldset>
                                    <div class="message form-field">
                                        {{ form_comentario.contenido.label_tag }} 
                                        {{ form_comentario.contenido }} 
                                        {% if form_comentario.contenido.errors %}
                                            <ul class="errorlist">
                                            {% for error in form_comentario.contenido.errors %}
                                                    <li>{{ error }}</li>
                                                {% endfor %}
                                            </ul>
                                        {% endif %}
                                    </div>
                                    <input name="submit" id="submit" class="btn btn--primary btn-wide btn--large full-width" value="Añadir Comentario" type="submit">
                                </fieldset>
                            </form>
                        {% else %}
                            <p>Debes <a href="{% url 'usuarios:path_login' %}">iniciar sesión</a> para comentar.</p>
                        {% endif %}
                </div>
            </div>
                        
        </div>
    </main>
</div> 



{% endblock content %}

Repositorioblog/Blog_noticias/templates/articulos/editar_articulo.html
{% extends 'base.html' %}
{% load static %}

{% block content %}


        <!-- inicio modulo
        ================================================== -->


        
    

    <div class="s-content content">
        <main class="row content__page">
            <article class="column large-full entry format-standard">
                <h2>Editar Artículo: {{ articulo.titulo }}</h2>
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}

                    {{ form.as_p }}

                    <button type="submit" class="btn btn--primary">Guardar cambios</button>
                    <a href="{% url 'articulos:path_detalle_articulo' articulo_slug=articulo.slug %}" class="btn btn--secondary">Cancelar</a>
                </form>
            </article>
        </main>
    </div>


    {{form.media}}


{% endblock content %}

Repositorioblog/Blog_noticias/templates/articulos/lista_articulos.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

                                <!-- ************ inicio articulos ************  -->
<div class="s-content"> 

    <header class="listing-header">
        {% if categoria_actual %}
            <h1 class="h2">{{ categoria_actual.nombre }}<!-- nombre de la cat cuando se filtra -->
        {% elif colectividad_actual %}
            {{ colectividad_actual.nombre }}
        {% else %}
            Cultura
        {% endif %}
            
            <form method="GET" action=""> 
                {% if request.GET.page %}  <!-- para mantener la pagina -->
                    <input type="hidden" name="page" value="{{ request.GET.page }}">
                {% endif %}

                    {% if current_category %} <!-- para mantener la categoria -->
                    <input type="hidden" name="categoria_slug" value="{{ current_category.slug }}">
                {% endif %}

                <div class="ss-custom-select" style="margin-top: 20px;">
                    <label for="order_by_select" class="ss-custom-select-label" >Ordenar por:</label>
                    <select style="max-width:fit-content; min-width:min-content px;" class="ss-custom-select-box" id="order_by_select" name="order_by" onchange="this.form.submit()" style="margin: top -30px;">
                        <option value="newest" {% if ordenar_por == 'newest' %}selected{% endif %}>Fecha (Más reciente)</option>
                        <option value="oldest" {% if ordenar_por == 'oldest' %}selected{% endif %}>Fecha (Más antiguo)</option>
                    </select>
                </div>
            </form>
    </header>
    
    <div class="masonry-wrap">

        <div class="masonry">

            <div class="grid-sizer"></div>
            
            {% for articulo in page_obj%} 

            <article class="masonry__brick entry format-standard animate-this">
                    
                <div class="entry__thumb">
                    <a href="{% url 'articulos:path_detalle_articulo' articulo.slug %}" class="entry__thumb-link">
                        <img src="{{ articulo.imagen.url }}" 
                                srcset="{{ articulo.imagen.url }}" alt="{{ articulo.titulo }}">
                    </a>
                </div>
                    
                <div class="entry__text">
                    <div class="entry__header">

                        <h2 class="entry__title"><a href="{% url 'articulos:path_detalle_articulo' articulo.slug %}">{{ articulo.titulo }}</a></h2>
                        <div class="entry__meta">
                            <span class="entry__meta-cat">
                                {% if articulo.colectividad %}
                                Por <a href="{% url 'articulos:path_lista_articulos_colectividad' colectividad_slug=articulo.colectividad.slug %}">{{ articulo.colectividad.nombre }}</a></li>
                                {% endif %} 
                                <br>
                                <a href="{% url 'articulos:path_lista_articulos' %}">Cultura</a> 
                                {% if articulo.categoria %}
                                <a href="{% url 'articulos:path_lista_articulos_categoria' categoria_slug=articulo.categoria.slug %}">{{ articulo.categoria.nombre }}</a>
                                {% endif %}
                            </span>
                            <span class="entry__meta-date">
                                <a href="{% url 'articulos:path_detalle_articulo' articulo.slug %}">{{ articulo.creado|date:"d M Y"}}</a>
                            </span>
                        
                        </div>
                        
                    </div>
                    <div class="entry__excerpt">
                        <p> {{ articulo.descripcion }} </p>
                        <br>
                        <a href="{% url 'articulos:path_detalle_articulo' articulo.slug %}" class="btn btn--primary u-fullwidth">Leer más</a>
                    </div>
                </div>

            </article> {% empty %} {# Si page_obj está vacío #}
                <p>No hay artículos disponibles en esta categoría.</p>
            
                            
                                <!-- end article -->

            {% endfor %}

        </div> <!-- end masonry -->

    </div> <!-- end masonry-wrap -->

    <div class="row">
        <div class="column large-full">
            <nav class="pgn">
                <ul>
                    {% if page_obj.has_previous %}    
                        <li><a class="pgn__prev" href="?page={{ page_obj.previous_page_number }}">Anterior</a></li>
                    {% else %}
                        <li><span class="pgn__prev">Anterior</span></li>
                    {% endif %}

                    {% for i in page_obj.paginator.page_range %}
                        {% if page_obj.number == i %}
                            <li><span class="pgn__num current">{{ i }}</span></li>
                        {% else %}
                            <li><a class="pgn__num" href="?page={{ i }}">{{ i }}</a></li>
                        {% endif %}
                    {% endfor %}
                    
                        {% if page_obj.has_next %}
                        <li><a class="pgn__next" href="?page={{ page_obj.next_page_number }}">Siguiente</a></li>
                    {% else %}
                        <li><span class="pgn__next">Siguiente</span></li>
                    {% endif %}
                            
                </ul>
            </nav>
        </div>
    </div>

</div> <!-- end s-content -->

{% endblock content %}