Repositorioblog/Blog_noticias/Blog_noticias/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views




from . import views

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', views.home, name = 'path_home'),
    
    path('cultura/', include('articulos.urls')),

    path('ckeditor/', include('ckeditor_uploader.urls')),

    path('comentarios/', include('comentarios.urls')),
    
    path('usuarios/', include('usuarios.urls')),

    path('nosotros/', include('nosotros.urls')),

    path('contacto/', include('contacto.urls')),

    path('agenda/', include('agenda.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Repositorioblog/Blog_noticias/apps/agenda/urls.py
from django.urls import path
from . import views

app_name = 'agenda'

urlpatterns = [
    path('', views.lista_eventos, name='path_lista_eventos'),

    path('categoria/<slug:categoria_slug>/', views.lista_eventos, name = 'path_lista_eventos_categoria'),

    path('colectividad/<slug:colectividad_slug>/', views.lista_eventos, name='path_lista_eventos_colectividad'),    
    
    path('evento/<slug:evento_slug>/', views.detalle_evento, name='path_detalle_evento'),

    path('crear/', views.CrearEvento.as_view(), name='path_crear_evento'),

    path('<slug:evento_slug>/editar/', views.EditarEvento.as_view(), name='path_editar_evento'),
    
    path('<slug:evento_slug>/borrar/', views.BorrarEvento.as_view(), name='path_borrar_evento'),

    path('<slug:evento_slug>/asistir/', views.AsistirEvento.as_view(), name='path_asistir_evento'),

]

Repositorioblog/Blog_noticias/apps/contacto/urls.py
from django.urls import path
from . import views

app_name = 'contacto'

urlpatterns = [

    path('', views.lista_contacto, name = 'path_contacto_main'),

    #crear, editar, borrar y detalle igual que about us pal futuro

]

Repositorioblog/Blog_noticias/apps/nosotros/urls.py
from django.urls import path
from . import views

app_name = 'nosotros'

urlpatterns = [

    path('', views.lista_nosotros, name = 'path_nosotros_main'),

    path('crear/', views.CrearNosotros.as_view(), name='path_crear_nosotros'),

    

    
  
    path('<slug:nosotros_slug>/editar/', views.EditarNosotros.as_view(), name='path_editar_nosotros'),

    path('<slug:nosotros_slug>/borrar/', views.BorrarNosotros.as_view(), name='path_borrar_nosotros'),

    path('<slug:nosotros_slug>/', views.detalle_nosotros, name='path_detalle_nosotros'),
    


]

Repositorioblog/Blog_noticias/apps/usuarios/urls.py
from django.urls import path

from django.contrib.auth import views as auth

from . import views

app_name = 'usuarios'



urlpatterns = [
    path('login/', auth.LoginView.as_view(template_name='usuarios/login.html'),name = 'path_login'),

    path('logout/', auth.LogoutView.as_view(),name = 'path_logout'),

    path('registro/',views.RegistroUsuario.as_view(), name = 'path_registro'),
]

    

Repositorioblog/Blog_noticias/templates/base.html
{% load static %}

<!DOCTYPE html>
<html class="no-js" lang="en">
<head>
    <!--- basic page needs
    ================================================== -->
    <meta charset="utf-8">
    <title>Unión de Colectividades</title>
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- mobile specific metas
    ================================================== -->
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSS
    ================================================== -->
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <link rel="stylesheet" href="{% static 'css/vendor.css' %}">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">

    <!-- script
    ================================================== -->
    <script src="{% static 'js/modernizr.js' %}"></script>

    <!-- favicons
    ================================================== -->
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'images/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'images/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'images/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'site.webmanifest' %}">
</head>

<body>
    <!-- preloader
    ================================================== -->
    <div id="preloader">
        <div id="loader" class="dots-fade">
            <div></div>
            <div></div>
            <div></div>
        </div>
    </div>

    <div id="top" class="s-wrap site-wrapper">
        <!-- site header
        ================================================== -->
        <header class="s-header">
            <div class="header__top">
                <div class="header__logo">
                    <a class="site-logo" href="{% url 'path_home' %}">
                        <img src="{% static 'images/logouniconcolectividades.png' %}" alt="Homepage">
                    </a>
                </div>

                

                <!-- toggles -->
                <a href="#0" class="header__menu-toggle"><span>Menu</span></a>
            </div> <!-- end header__top -->

            <nav class="header__nav-wrap">
                <ul class="header__nav">
                    <li class="current"><a href="{% url 'path_home' %}" title="">Inicio</a></li>
                    <li class="has-children">
                        <a href="{% url 'articulos:path_lista_articulos' %}" title="">Cultura</a>
                        <ul class="sub-menu">
                            {% if user.is_staff %}
                            <li><a href="{% url 'articulos:path_crear_articulo' %}">Crear Artículo</a></li>

                            {% endif %}

                            <li><a href="{% url 'articulos:path_lista_articulos' %}">Ver todos</a></li>
                            {% for cat in categorias_cultura %}
                                <li>
                                    <a href="{% url 'articulos:path_lista_articulos_categoria' categoria_slug=cat.slug %}">
                                        {{ cat.nombre }}
                                    </a>
                                </li>
                            {% endfor %}
                        </ul>
                    </li>
                    <li class="has-children">
                        <a href="{% url 'agenda:path_lista_eventos' %}" title="">Eventos</a>
                        <ul class="sub-menu">

                            {% if user.is_staff %}
                            <li><a href="{% url 'agenda:path_crear_evento' %}">Crear Evento</a></li>

                            {% endif %}
                            <li><a href="{% url 'agenda:path_lista_eventos' %}">Ver todos</a></li>

                            {% for cat in categorias_eventos %}
                                <li>
                                    <a href="{% url 'agenda:path_lista_eventos_categoria' categoria_slug=cat.slug %}">
                                        {{ cat.nombre }}
                                    </a>
                                </li>
                            {% endfor %}

                        </ul>
                    </li>
                    <li><a href="{% url 'nosotros:path_nosotros_main' %}" title="">Sobre Nosotros</a></li>
                    <li><a href="{% url 'contacto:path_contacto_main' %}" title="">Contacto</a></li>
                </ul> <!-- end header__nav -->

                <ul class="header__nav">
                    {% if user.is_authenticated %}
                        <li><a class="li-Hola-Usuario">Hola, &nbsp;{{ user.username }}</a></li>
                        <li>
                            <form method="POST" action="{% url 'usuarios:path_logout' %}">
                                {% csrf_token %}
                                <button type="submit" class="cerrar-sesion-btn">Cerrar Sesión</button>
                            </form>
                        </li>
                    {% else %}
                        <li><a href="{% url 'usuarios:path_login' %}" title="">Iniciar Sesión</a></li>
                        <li><a href="{% url 'usuarios:path_registro' %}" title="">Registrarse</a></li>
                    {% endif %}
                </ul>
            </nav> <!-- end header__nav-wrap -->
        </header> <!-- end s-header -->

        <!-- Contenido dinámico -->
        {% block content %}
        {% endblock content %}

        <!-- footer
        ================================================== -->

        

        <footer class="s-footer">
            <div class="row">
                <div class="column large-full footer__content">
                    <div class="footer__copyright">
                        <ul class="footer__social">
                            <li class="ss-facebook">
                                <a href="https://www.facebook.com/profile.php?id=100064456398762">
                                    <span class="screen-reader-text">Facebook</span>
                                </a>
                            </li>
                            <li class="ss-instagram">
                                <a href="https://www.instagram.com/unioncolectividadesdelchaco/">
                                    <span class="screen-reader-text">Instagram</span>
                                </a>
                            </li>
                            <li class="ss-twitter">
                                <a href="https://x.com">
                                    <span class="screen-reader-text">Twitter</span>
                                </a>
                            </li>
                            <li class="ss-pinterest">
                                <a href="https://pinterest.com">
                                    <span class="screen-reader-text">Pinterest</span>
                                </a>
                            </li>
                        </ul>
                        <br>
                        <span>Unión de Colectividades, CHACO - 2025</span>
                        <span>Design by <a href="https://www.styleshout.com/">StyleShout</a></span>
                    </div>
                </div>
            </div>

            <div class="go-top">
                <a class="smoothscroll" title="Back to Top" href="#top"></a>
            </div>
        </footer>

    </div> <!-- end s-wrap -->


    <!-- Java Script
    ================================================== -->
    <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
    <script src="{% static 'js/plugins.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>

Repositorioblog/Blog_noticias/templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<!-- inicio modulo
================================================== -->

<div class="s-content">

    <!-- Sección de Artículos -->
    <header class="listing-header">
        <h1 class="h2">Últimos Artículos: Cultura</h1>
    </header>
    
    <div class="masonry-wrap">
        <div class="masonry">
            <div class="grid-sizer"></div>
            
            {% for articulo in ultimos_articulos %}
            <article class="masonry__brick entry format-standard animate-this">
                <div class="entry__thumb">
                    <a href="{% url 'articulos:path_detalle_articulo' articulo_slug=articulo.slug %}" class="entry__thumb-link">
                        <img src="{{ articulo.imagen.url }}" 
                             srcset="{{ articulo.imagen.url }}" alt="{{ articulo.titulo }}">
                    </a>
                </div>
                <div class="entry__text">
                    <div class="entry__header">
                        <h2 class="entry__title">
                            <a href="{% url 'articulos:path_detalle_articulo' articulo_slug=articulo.slug %}">{{ articulo.titulo }}</a>
                        </h2>
                        <div class="entry__meta">
                            <span class="entry__meta-cat">
                                {% if articulo.colectividad %}
                                    Por <a href="{% url 'articulos:path_lista_articulos_colectividad' colectividad_slug=articulo.colectividad.slug %}">{{ articulo.colectividad.nombre }}</a>
                                {% endif %}
                                <a href="{% url 'articulos:path_lista_articulos' %}">Cultura</a>
                                {% if articulo.categoria %}
                                    <a href="{% url 'articulos:path_lista_articulos_categoria' categoria_slug=articulo.categoria.slug %}">{{ articulo.categoria.nombre }}</a>
                                {% endif %}
                            </span>
                            <span class="entry__meta-date">
                                {{ articulo.creado|date:"d M Y" }}
                            </span>
                        </div>
                    </div>
                    <div class="entry__excerpt">
                        <p>{{ articulo.descripcion|truncatewords:30 }}</p>
                        <br>
                        <a href="{% url 'articulos:path_detalle_articulo' articulo.slug %}" class="btn btn--primary u-fullwidth">Leer más</a>
                    </div>
                </div>
            </article>
            {% empty %}
            <p>No hay artículos disponibles.</p>
            {% endfor %}
        </div> <!-- end masonry -->
    </div> <!-- end masonry-wrap -->

    <div class="row">
        <div class="column large-full">
            <div class="entry__more-btn">
                <a href="{% url 'articulos:path_lista_articulos' %}" class="btn btn--primary">Ver más</a>
            </div>
        </div>
    </div>
<hr>
<br>
    <!-- Sección de Eventos -->
    <header class="listing-header">
        <h1 class="h2">Próximos Eventos</h1>
    </header>
    
    <div class="masonry-wrap">
        <div class="masonry">
            <div class="grid-sizer"></div>
            
            {% for evento in proximos_eventos %}
            <article class="masonry__brick entry format-standard animate-this">
                <div class="entry__thumb">
                    <a href="{% url 'agenda:path_detalle_evento' evento_slug=evento.slug %}" class="entry__thumb-link">
                        <img src="{{ evento.imagen.url }}" 
                             srcset="{{ evento.imagen.url }}" alt="{{ evento.titulo }}">
                    </a>
                </div>
                <div class="entry__text">
                    <div class="entry__header">
                        <h2 class="entry__title">
                            <a href="{% url 'agenda:path_detalle_evento' evento_slug=evento.slug %}">{{ evento.titulo }}</a>
                        </h2>
                        <div class="entry__meta">
                            <span class="entry__meta-cat">
                                {% if evento.colectividad %}
                                    Por <a href="{% url 'agenda:path_lista_eventos_colectividad' colectividad_slug=evento.colectividad.slug %}">{{ evento.colectividad.nombre }}</a>
                                {% endif %}
                                <a href="{% url 'agenda:path_lista_eventos' %}">Eventos</a>
                                {% if evento.categoria %}
                                    <a href="{% url 'agenda:path_lista_eventos_categoria' categoria_slug=evento.categoria.slug %}">{{ evento.categoria.nombre }}</a>
                                {% endif %}
                            </span>
                            <span class="entry__meta-date">
                                {{ evento.fecha|date:"d M Y" }}
                                {% if evento.hora %} a las {{ evento.hora|time:"H:i" }}{% endif %}
                            </span>
                        </div>
                    </div>
                    <div class="entry__excerpt">
                        <p>{{ evento.descripcion|truncatewords:30 }}</p>
                    </div>
                </div>
            </article>
            {% empty %}
            <p>No hay eventos próximos disponibles.</p>
            {% endfor %}
        </div> <!-- end masonry -->
    </div> <!-- end masonry-wrap -->

    <div class="row">
        <div class="column large-full">
            <div class="entry__more-btn">
                <a href="{% url 'agenda:path_lista_eventos' %}" class="btn btn--primary">Ver más</a>
            </div>
        </div>
    </div>

</div> <!-- end s-content -->

{% endblock content %}